FROM adamdecaf/dev-setup:latest

# apt-get install w3m
# git clone git@github.com:adamdecaf/custom-emacs-files.git /root/.emacs.d/custom/

# mkdir -p /root/src/third-party && \
# git clone git@github.com:paulp/sbt-extras.git /root/src/third-party/sbt/ && \
# ln -s /root/src/third-party/sbt/sbt /root/bin/sbt
